# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development: 
  d78cc2d7bd6e4f7afd0342cf66e8f98d4ee49add2d12b1a9fbb56690d1221c15aa3b42f084c9b3e98f82858081de3b2a48c8052c16963656f654b64b1e94e9f2
  
test:
  secret_key_base: 3c4e20e02b34a70e6f613c7eae78ed13962d039b61348ddf7a31c549fe919193c8aecf2baa3a0912153862907f97e067eff3a22841f05dd5c742dc186aa09b7f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
